name: xmpp
version: 0.0.1
author: Max Horstmann
description: '** work in progress, not ready for production use yet *  Lightweight
  XMPP client for Dart. With support for Facebook chat server.'
homepage: https://github.com/MaxHorstmann/dart-xmpp
dependencies:
  crypto: 0.6.13
